### ISSUE TITLE
[To-do] Have a minimal pathogen agnostic ShinyApp structure

### ISSUE THREAD

**Issue by rafalopespx** [rafalopespx/pathogen_tracker#1]
Breakup of to-do tasks to be filled as the work progresses:
- [ ] Templating, with a general structure but still agnostic any pathogen
  - [ ] Minimal ShinyApp structure
     - [ ] Folders structure
     - [ ] Headup codes
     - [ ] Config scripts
  - [ ] Make a toy dataset for the MVP (Covid?)
  - [ ] Minimal viable product for toy dataset
     - [ ] Cases count per time (Epi data)
       - [ ] Monthly/Weekly/Daily (Agnostic time period)
       - [ ] Cumulative cases
     - [ ] Genomic sequence counts (Output)
     - [ ] Variant count per time (Pathogen data)
     - [ ] Ct per lineage
     - [ ] Rt values by variant
     - [ ] NextStrain
     - [ ] NextClade
- [ ] Test the template to be able to reproduce something similar to CovidTrackerCT from [here](https://github.com/rafalopespx/covidtrackerct)
